name: paramtools-ex
channels:
  - conda-forge
  - pslmodels
dependencies:
  - paramtools
  - marshmallow
  - numba
  - "numpy>=1.13"
  - "python-dateutil>=2.8.0"
  - pytest
  - taxcalc
  - pip:
    - pre-commit
    - black
    - flake8
